export const dimensions = [
  { key: 'individualism', label: 'Individualism' },
  { key: 'collectivism', label: 'Collectivism' },
  { key: 'decentralization', label: 'Decentralization' },
  { key: 'privacy', label: 'Privacy' },
  { key: 'security', label: 'Security' },
];

export const principleScores = [
  {
    principle: 'Personhood',
    individualism: 90,
    collectivism: 30,
    decentralization: 70,
    privacy: 60,
    security: 80,
  },
  {
    principle: 'Ownership',
    individualism: 100,
    collectivism: 20,
    decentralization: 90,
    privacy: 80,
    security: 90,
  },
  {
    principle: 'Privacy',
    individualism: 80,
    collectivism: 40,
    decentralization: 80,
    privacy: 100,
    security: 70,
  },
  {
    principle: 'Information',
    individualism: 50,
    collectivism: 80,
    decentralization: 90,
    privacy: 30,
    security: 40,
  },
  {
    principle: 'Capital',
    individualism: 60,
    collectivism: 70,
    decentralization: 85,
    privacy: 20,
    security: 50,
  },
  {
    principle: 'Public Goods',
    individualism: 20,
    collectivism: 100,
    decentralization: 60,
    privacy: 40,
    security: 50,
  },
  {
    principle: 'Security',
    individualism: 70,
    collectivism: 50,
    decentralization: 70,
    privacy: 70,
    security: 100,
  },
  {
    principle: 'Accountability',
    individualism: 40,
    collectivism: 90,
    decentralization: 50,
    privacy: 50,
    security: 80,
  },
  {
    principle: 'Earth',
    individualism: 10,
    collectivism: 100,
    decentralization: 40,
    privacy: 10,
    security: 30,
  },
  {
    principle: 'Resilience',
    individualism: 60,
    collectivism: 80,
    decentralization: 100,
    privacy: 60,
    security: 90,
  },
];
